### PR TITLE
Added the maven-bundle-plugin to the build

### PR DESCRIPTION
**Pull request by klemensedler**
It would be great if markdown4j could be provided as OSGi-enabled JAR at maven central.

The changes I introduced enhance the resulting MANIFEST.MF with OSGi specific information.

### CODE REVIEW

**Comment by jdcasey** [comment]
Is there any chance you can restore the formatting in the pom.xml? It's pretty difficult to see what changes you've made (beyond the new section near the bottom). Otherwise, I'll just need to reformat it after merging this. I use 2-space indentation, fwiw.

**Comment by klemensedler** [comment]
Thanks for coming back to me! 

Of course, I have now switched to 2 space indentation. Sorry, should have noticed that ;-)

All I did was define a format for the timestamp (properties section) and add the maven-bundle-plugin that writes a few additional lines into the manifest.mf.

**Comment by mstahv** [comment]
@jdcasey, do you plan to build a new release at some point to Maven central? We are wondering if we should make a workaround to a library that uses markdown4j or should we wait for new osgi compatible release.

**Comment by jdcasey** [comment]
Sorry, I lost track of this. I'll try to get a new release out today.

**Comment by mstahv** [comment]
Excellent, thanks!

**Comment by jdcasey** [comment]
Okay, the release is done, and should appear on central soonish.

**Pull request merged**
